project:
  type: website
  output-dir: docs
  resources:
    - "get-started/new-cars.csv"
  render:
    - about.qmd
    - index.qmd
    - learn-more/*
    - get-started/index.qmd
    - get-started/version.qmd
    - get-started/deploy.qmd
    - get-started/monitor.qmd
    - pythondocs/*

website:
  title: "MLOps with vetiver"
  description: "Version, share, deploy, and monitor your R and Python models"
  open-graph: true
  twitter-card: true
  site-url: https://vetiver.rstudio.com
  repo-url: https://github.com/rstudio/vetiver.rstudio.com
  repo-actions: [edit, issue]
  page-navigation: true
  favicon: "images/favicon.ico"
  page-footer:
    left: |
      Proudly supported by
      [![](https://www.rstudio.com/wp-content/uploads/2018/10/RStudio-Logo-flat.svg){fig-alt="RStudio" width=65px}](https://www.rstudio.com)
    center:
      - text: "About"
        href: about.qmd
    right:
      - icon: github
        href: https://github.com/rstudio/vetiver.rstudio.com
        aria-label: Vetiver site GitHub

  navbar:
    background: primary
    pinned: true
    logo: "images/logo_small.png"
    left:
      - href: index.qmd
        text: Home
      - text: Get Started
        href: get-started/index.qmd
      - text: Learn More
        menu:
          - href: learn-more/parity-checklist.qmd
            text: "Function parity for R and python"
          - href: learn-more/model-card.qmd
            text: "Model cards for transparent, responsible reporting"
          - href: learn-more/deploy-with-docker.qmd
            text: "Deploy with Docker"
      - href: https://rstudio.github.io/vetiver-r/reference/
        text: R Function Reference
      - href: pythondocs/index.qmd
        text: Python Function Reference


  sidebar:
    - id: get-started
      title: Get Started
      collapse-level: 2
      style: "floating"
      align: left
      contents:
        - href: get-started/index.qmd
        - href: get-started/version.qmd
        - href: get-started/deploy.qmd
        - href: get-started/monitor.qmd

    - id: learn-more
      title: Learn More
      collapse-level: 3
      align: left
      contents:
        - href: learn-more/parity-checklist.qmd
        - href: learn-more/model-card.qmd
        - href: learn-more/deploy-with-docker.qmd

    - id: pythondocs
      title: Python Docs
      contents:
        - href: pythondocs/index.qmd
          text: Vetiver for Python
        - section: "Version"
          contents:
            - pythondocs/VetiverModel.qmd
            - pythondocs/vetiver_pin_write.qmd
            - pythondocs/vetiver_create_prototype.qmd
        - section: "Deploy"
          contents:
            - pythondocs/VetiverAPI.qmd
            - pythondocs/vetiver_endpoint.qmd
            - pythondocs/predict.qmd
            - pythondocs/write_app.qmd
            - pythondocs/write_docker.qmd
            - pythondocs/deploy_rsconnect.qmd
        - section: "Monitor"
          contents:
            - pythondocs/compute_metrics.qmd
            - pythondocs/pin_metrics.qmd
            - pythondocs/plot_metrics.qmd
        - section: "Handlers"
          contents:
            #- pythondocs/BaseHandler.qmd
            - pythondocs/SKLearnHandler.qmd
            - pythondocs/TorchHandler.qmd
            - pythondocs/StatsmodelsHandler.qmd
            - pythondocs/XGBoostHandler.qmd
        - section: "Advanced Usage"
          contents: 
            - pythondocs/custom_handler.md

quartodoc:
  style: pkgdown
  dir: pythondocs
  out_index: _api_index.qmd
  package: vetiver
  sections:
    # TODO: figure out preface and Advanced Usage section
    - title: ""
      desc: ""
      contents:
        - VetiverModel
        - vetiver_pin_write
        - vetiver_create_prototype
        - model_card.model_card

    - title: Deploy
      desc: ""
      contents:
        - VetiverAPI
        # - VetiverAPI.run
        # - VetiverAPI.vetiver_post
        - vetiver_endpoint
        - predict
        - write_app
        - write_docker.write_docker
        - deploy_rsconnect

    - title: Monitor
      desc: ""
      contents:
        - compute_metrics
        - pin_metrics
        - plot_metrics

    - title: Model Handlers
      desc: ""
      contents:
        - SKLearnHandler
        - TorchHandler
        - StatsmodelsHandler
        - XGBoostHandler

filters:
  - grouped-tabsets
  - interlinks

interlinks:
  sources:
    vetiver:
      url: "/"
      inv: null
      fallback: objects.json

format:
  html:
    theme: [sandstone, custom.scss]
    css: styles.css
